[compiler.solc]
ignore_paths = ["node_modules", ".woke-build", "venv", "lib"]
include_paths = ["node_modules"]
remappings = [
  "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
  "@uniswap/v4-periphery/=lib/v4-periphery/",
  "solmate/=lib/v4-periphery/lib/solmate/src/",
  "forge-std/=lib/v4-periphery/forge-std/src/",
  "@openzeppelin/=lib/v4-periphery/lib/openzeppelin-contracts/"
]
optimizer = {enabled = true, runs = 900}

[detectors]
exclude = []
ignore_paths = ["node_modules", ".woke-build", "venv", "lib"]

[testing]
cmd = "anvil"


[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent --code-size-limit 2128000"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""
