name: Automated fuzzing

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: oogali/wokefuzz@v0.0.3
